version: '3.9'

services:
  node-app:
    build: ./
    container_name: node-app
    networks:
      - intranet
    volumes:
      - ./app:/code/app
    ports:
      - "5173:5173"
      - "2222:22"

networks:
  intranet:
    driver: bridge